apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook-classic-prod
resources:
  - ../../base
images:
  - name: ghcr.io/jake-painter/guestbook
    newTag: v0.1.0  # Kargo rewrites newTag here on promotion (committed to main)